// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $CompleteLeadForm from "./islands/CompleteLeadForm.tsx";
import * as $FAQ from "./islands/FAQ.tsx";
import * as $LeadForm from "./islands/LeadForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/CompleteLeadForm.tsx": $CompleteLeadForm,
    "./islands/FAQ.tsx": $FAQ,
    "./islands/LeadForm.tsx": $LeadForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
